Firebase case study
NoroffFEU/development-platforms pull request #17
Opened 2023-02-10 11:31 UTC by AugustWahlberg

Course Assignment - Development Platforms

2023-02-13 06:26 UTC, Fermain requested changes
This is a well written case study with only minor mistakes to correct. It is a good length, provides an interesting overview of this useful platform and uses the correct formatting throughout!

2023-02-13 06:26 UTC, Fermain commented on firebase-case-study.md
> +**Appwrite** is also popular BaaS, but distinguish from Firebase in a few ways. Firebase is a cloud-based platform hosted by Google and offers a paid service with a free tier, while Appwrite is a sel
```suggestion
**Appwrite** is also popular BaaS, but is distinguished from Firebase in a few ways. Firebase is a cloud-based platform hosted by Google and offers a paid service with a free tier, while Appwrite is a self-hosted platform that is open-source and free to use but requires hosting and setup costs. Firebase has a more straightforward setup process, but provides limited control over your backend infrastructure and data, whereas Appwrite provides greater control but requires more advanced setup. Appwrite also focuses on the APIs. This makes it well-suited for developers who want to build APIs or integrate their applications with other APIs such as server-side validation, image and video manipulation, and more.
```

2023-02-13 06:26 UTC, Fermain commented on firebase-case-study.md
> +## Prizing
```suggestion
## Pricing
```

2023-02-13 06:26 UTC, Fermain commented on firebase-case-study.md
> +Firebase offers a free tier with limited usage of each feature, and flexible payment options, such as monthly and annual billing. This allows you to get started and evaluate your app's needs without
```suggestion
Firebase offers a free tier with limited usage of each feature, and flexible payment options, such as monthly and annual billing. This allows you to get started and evaluate your app's needs without immediate costs. You will find more detailed information [here](https://firebase.google.com/pricing).
```

2023-02-13 06:26 UTC, Fermain commented on firebase-case-study.md
> +Firebase offers a free tier with limited usage of each feature, and flexible payment options, such as monthly and annual billing. This allows you to get started and evaluate your app's needs without
Please could you pick at least one of the other firebase case studies to peer review.

2023-02-14 18:16 UTC, AugustWahlberg commented
Thanks for the helpful feedback!  Added per review to this Firebase case study: https://github.com/NoroffFEU/development-platforms/pull/33

2023-02-28 09:49 UTC, Fermain approved these changes
Feedback is in Moodle, well done and thanks again

2023-02-28 09:49 UTC, merged