Strapi
NoroffFEU/development-platforms pull request #20
Opened 2023-02-12 21:11 UTC by NehGuk

Could you please let me know if my case study is heading in the right direction? I'm pretty much done but intend to add a final chapter with a quick demonstration on how to set up a self-hosted API with PostgreSQL.

2023-02-13 13:04 UTC, Fermain requested changes
This is going in the right direction, but I have one major intervention. I am instructing students not to use first person directly, and switch to `The author...` where that isn't possible. I don't think that will be a huge issue for you and its a matter of consistency more than anything else.

2023-02-13 13:04 UTC, Fermain commented on strapi.md
> +_Compare the product to other products in the same category, if applicable._
```suggestion
```

2023-02-13 13:05 UTC, Fermain commented
Please mark this as a draft

2023-02-15 20:16 UTC, NehGuk commented
Thank you for the feedback, Oliver. I have edited out the use of the first person. I have also included the missing final chapters.

2023-03-06 09:26 UTC, Fermain approved these changes
A detailed, well researched case study that provides a well rounded introduction to Strapi. This is a tool that many of our students and teachers use, so this case study will be of great use to interested parties in future.

The review process shows that you are able to take on constructive feedback and implement this in your work without issues. Given your background in technical journalism, this was not a surprise to me :)

Well done and thanks for this great quality contribution!

2023-03-06 09:26 UTC, merged