Azure case study
NoroffFEU/development-platforms pull request #276
Opened 2024-04-25 09:50 UTC by ArneBHuset

Case study about Microsoft Azure ready for review

2024-05-13 15:28 UTC, sulenchy commented on src/content/docs/webdev-hosting/azure/azure.md
> +## Bacground
There is a typo here

2024-05-13 15:35 UTC, sulenchy requested changes
@ArneBHuset 
Thanks for the effort you put into raising this PR. Unfortunately, this is a duplicate. There are already three case studies in the codebase, and according to the brief of the CA, you are expected to either consolidate the existing ones into one or delve deeper into one of the features of Azure in your research.

Please fix the issue and get back to me within the next 24 hours.

2024-05-13 15:45 UTC, ArneBHuset commented
Hi,

I asked Oliver if i could write about Azure since i wanted to learn more about the basis of it and got a thumbs up.

Regards
Arne

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Abudu Abidun Sulaiman ***@***.***>
Sent: Monday, May 13, 2024 5:35:45 PM
To: NoroffFEU/development-platforms ***@***.***>
Cc: ArneBHuset ***@***.***>; Mention ***@***.***>
Subject: Re: [NoroffFEU/development-platforms] Azure case study (PR #276)


@sulenchy requested changes on this pull request.

@ArneBHuset<https://github.com/ArneBHuset>
Thanks for the effort you put into raising this PR. Unfortunately, this is a duplicate. There are already three case studies in the codebase, and according to the brief of the CA, you are expected to either consolidate the existing ones into one or delve deeper into one of the features of Azure in your research.

Please fix the issue and get back to me within the next 24 hours.

—
Reply to this email directly, view it on GitHub<https://github.com/NoroffFEU/development-platforms/pull/276#pullrequestreview-2053050837>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6Q4ZQAHOKEA4YPRG25IEWLZCDMVDAVCNFSM6AAAAABGYQ4FDWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJTGA2TAOBTG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-13 16:05 UTC, sulenchy commented
@ArneBHuset That is understandable. The issue with your PR is that it duplicates an existing case study and there is a section in the brief that advises you on what to do if someone has written about your topic. See

```
If there is an existing case study discussing your chosen product, consider these contribution options:

Create a video companion to an existing written case study
Create a text companion to an existing video case study
Pick a particular feature, offering or aspect of this product to deep dive into
Consolidate duplicate case studies into a single case study on that subject
```

To pass the CA, you need to comply with the requirements stated in the brief.

2024-05-13 16:12 UTC, ArneBHuset commented
I asked if i could write about Azure from the beginning instead of building on top, seeing as i have to grasp the basics to be able to comprehend anything else. I am very interested in Azure, and this was the appropriate way to learn about it for me, i would see no purpose in skipping all the basics just to continue with a more detailed case study. I saw the requirements, therefore i asked Oliver if it would be okay and i got a thumbs up

-Arne

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Abudu Abidun Sulaiman ***@***.***>
Sent: Monday, May 13, 2024 6:05:41 PM
To: NoroffFEU/development-platforms ***@***.***>
Cc: ArneBHuset ***@***.***>; Mention ***@***.***>
Subject: Re: [NoroffFEU/development-platforms] Azure case study (PR #276)


@ArneBHuset<https://github.com/ArneBHuset> That is understandable. The issue with your PR is that it duplicates an existing case study and there is a section in the brief that advises you on what to do if someone has written about your topic. See

If there is an existing case study discussing your chosen product, consider these contribution options:

Create a video companion to an existing written case study
Create a text companion to an existing video case study
Pick a particular feature, offering or aspect of this product to deep dive into
Consolidate duplicate case studies into a single case study on that subject


To pass the CA, you need to comply with the requirements stated in the brief.

—
Reply to this email directly, view it on GitHub<https://github.com/NoroffFEU/development-platforms/pull/276#issuecomment-2108107391>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6Q4ZQAPJ4NQDYOW27ZNEQTZCDQFLAVCNFSM6AAAAABGYQ4FDWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBYGEYDOMZZGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-13 19:12 UTC, Fermain commented
I recall discussing it, bringing up the fact that many have already chosen this and suggesting focusing on one particular azure product in more detail. @ArneBHuset do you think that's a fair recollection of our chat?

2024-05-14 12:33 UTC, sulenchy commented
Closed this because

2024-05-14 12:33 UTC, closed without merging

2024-05-14 12:34 UTC, sulenchy commented
I closed this because the PR duplicated an existing Azure case study