Travis CI case-study
NoroffFEU/development-platforms pull request #282
Opened 2024-04-28 19:22 UTC by Ramsnes

Adds deep-dive into case-study of Travis CI.

2024-05-13 09:36 UTC, sulenchy requested changes
@Ramsnes 
This write-up looks good to me. The presentation and tone are awesome and beginner-friendly. Also, good job on adding an image to boost the level of comprehension of the write-up.

However, I recommend you add a sidebar for the CI of Travis in the `astro-config.mjs`. Additionally, the build is failing, which will prevent me from merging the PR. I suggest you reach out to @jaaneh  regarding this matter.

2024-05-13 18:59 UTC, jaaneh commented
The CI fails becuase of the frontmatter. The `title`, `author` and `tags` fields need to be lowercase.

2024-05-17 07:48 UTC, sulenchy commented on src/content/docs/travis-ci/travis-ci-case-study.md
> +Title: Travis-CI Case Study
```suggestion
title: Travis-CI Case Study
```

2024-05-17 07:49 UTC, sulenchy commented on src/content/docs/travis-ci/travis-ci-case-study.md
> +Author: Morten Ramfjord, Ramsnes
```suggestion
author: Morten Ramfjord, Ramsnes
```

2024-05-17 07:49 UTC, sulenchy commented on src/content/docs/travis-ci/travis-ci-case-study.md
> +Tags: travisci, travis, travis-ci
```suggestion
tags: travisci, travis, travis-ci
```

2024-05-17 07:57 UTC, sulenchy commented
Fix it the frontmatter. Thanks @jaaneh

2024-05-17 07:57 UTC, sulenchy approved these changes
Looks good now

2024-05-17 07:57 UTC, merged