Tailwind case study/tailwind case study.md
NoroffFEU/development-platforms pull request #291
Opened 2024-05-14 08:51 UTC by Bavy89

tailwind case study - Bave Ado

2024-05-14 08:52 UTC, Bavy89 commented
tailwind case study - Bave Ado

2024-05-30 13:08 UTC, sulenchy requested changes
Good presentation. Straight to the point. However, it is not a good one for a beginner. It is lacking in the aspect of comprehension. A good write-up on a CSS framework should should some code couple with some image.
So, I recommend you demonstrate styling a component.

@Bavy89

2024-05-30 13:11 UTC, sulenchy reviewed
Also, I think this content should be kept in framework directory. You can create `css` sub-directory under `frameworks`. Like `/framworks/css/tailwind-case-study.md`

2024-05-30 17:52 UTC, Bavy89 commented
hi i have added new PR
https://github.com/Bavy89/development-platforms/blob/tailwind-case-study/tailwind-case-study.md/src/content/docs/tailwind-case-study/tailwind-case-study.md

2024-06-02 15:57 UTC, sulenchy commented on src/content/docs/tailwind-case-study/tailwind-case-study.md
> +
@Bavy89 Good job for implementing the feedback. However, now you have a duplicate. You need to remove the old one. The new one `[src/content/docs/frameworks/css/tailwind-case-study.md](https://github.com/NoroffFEU/development-platforms/pull/291/files#diff-caf64c6ec57e6a2da2e16c363b29a405b78d43a312deb01a1a482518e91ab174)` looks good to me.

2024-06-05 06:20 UTC, sulenchy approved these changes

2024-06-05 06:25 UTC, merged