Add author data to the docs collection
NoroffFEU/development-platforms pull request #302
Opened 2024-05-22 14:59 UTC by sulenchy

## Description

Add author data to the docs collection

2024-05-31 14:16 UTC, jaaneh requested changes
@sulenchy can you restore the package-lock file?

Also, can we handle displaying the Author component conditionally if there's an author included? Some case studies don't include one and will simply display _`Author: `_ without a name.

The actual h1 title loses some of it's styling also, wonder if we can restore the styling it has currently

2024-05-31 14:20 UTC, jaaneh requested changes

2024-05-31 14:20 UTC, jaaneh commented on src/components/CustomPageTitle.astro
> +  <em>Author: {author}</em>
```suggestion
  {author && (
    <em>Author: {author}</em>
  )}
```

2024-05-31 14:33 UTC, jaaneh requested changes

2024-05-31 14:33 UTC, jaaneh commented on src/components/CustomPageTitle.astro
> +</header>
```suggestion
---
const { title, author } = Astro.props.entry.data;
---

<h1 id="_top">{title}</h1>
{author && (
  <em>Author: {author}</em>
)}

<style>
  h1 {
    margin-top: 1rem;
    font-size: var(--sl-text-h1);
    line-height: var(--sl-line-height-headings);
    font-weight: 600;
    color: var(--sl-color-white);
  }
</style>
```

Let's conditionally render the author. This also restores default styling to the h1, both by applying manually and removing the wrapping <header>

2024-06-23 13:27 UTC, sulenchy commented
> @sulenchy can you restore the package-lock file?

Thanks for this comment @jaaneh. Did not notice it. I am restoring it ASAP.

2024-06-23 18:38 UTC, merged