ChatGPT case study
NoroffFEU/development-platforms pull request #5
Opened 2023-02-05 15:39 UTC by Melisa-Zorraindo

2023-02-06 08:06 UTC, Fermain requested changes
This is a really well researched and constructed case study about a subject that I find captivating. I have made some edits and suggestions, most of these are grammatical, a few tone and the rest are prompts.

Putting these aside, you have met the brief exactly as expected and delivered a high quality report.

2023-02-06 08:06 UTC, Fermain commented on chatGPT-case-study.md
> +ChatGPT is not the first chat bot in the market. Most company's customer service departments offer their users the possibility to solve their problems in real-time by chatting with a bot. Although th
```suggestion
ChatGPT is not the first chat bot in the market. Most companies' customer service departments offer their users the possibility to solve their problems in real-time by chatting with a bot. Although they use NLP and AI to understand what the customer says, they don't perform exceptionally well and more often than not the interaction leads to frustration for the human being. Their knowledge, moreover, is limited to the task they're designed to carry out. For example, [a car insurance chatbot can't do trigonometry, etc] ChatGPT, however, is not constrained to a specific activity, as it was trained using a large amount of data in different topics and styles.
```

2023-02-06 08:06 UTC, Fermain commented on chatGPT-case-study.md
> +Another significant improvement was made with the introduction of the Moderation API. The API help developers protect their applications against possible misuse by giving them free access to GPT-base
```suggestion
Another significant improvement was made with the introduction of the Moderation API. The API help developers protect their applications against possible misuse by giving them free access to GPT-based classifiers that detect undesired content. Bots like Tay and Blenderbot 3 would not have failed (at least so quickly) if they had been provided with a similar tool. ChatGPT is able to refuse to engage in offensive behaviour more efficiently than other similar bots. [This post from OpenAI](https://openai.com/blog/chatgpt/) shows a comparison between ChatGPT and InstructGPT where the different responses to the same malicious question reveal a clear advance.
```

2023-02-06 08:06 UTC, Fermain commented on chatGPT-case-study.md
> +As far as software development is concern, ChatGPT can write code faster than a human, but not more reliably. It requires human supervision to ensure it's working as intended. Even if you ask the cha
```suggestion
As far as software development is concerned, ChatGPT can write code faster than a human, but not more reliably. It requires human supervision to ensure it's working as intended. Even if you ask the chat bot to automate testing, these tests may also contain bugs. Replacing a human proves not to be so easy after all. Instead, this type of technology is most useful to boost productivity - to assist human beings in their daily tasks. It is obviously more efficient to ask a question and obtain a response in seconds than to post it on stackoverflow and wait for other developers to read our code and provide an answer. It is also easier to read one response than sift through dozens of pages from a Google search. This is why replacing an entire staff with bots is unlikely to happen in the near future.
```

2023-02-10 17:33 UTC, Melisa-Zorraindo commented on chatGPT-case-study.md
> +Furthermore, it cannot make internet searches to find new sources of information, being limited to the data it was used during its training. Although this was massive, the training finished in 2021 w
added

2023-02-10 17:33 UTC, Melisa-Zorraindo commented on chatGPT-case-study.md
> +The model also presents limitations in terms of server capacity. It is at times unreachable due to the amount of people trying to use the service at the same time. This is being addressed by offering
Added

2023-02-10 17:34 UTC, Melisa-Zorraindo commented on chatGPT-case-study.md
> +The above applies as well when learning to read errors. Errors may look like gibberish at first and you have to learn to interpret them. Being provided with an explanation that beginner developers ca
Added

2023-02-10 17:34 UTC, Melisa-Zorraindo commented on chatGPT-case-study.md
> +Focusing on software development, its ability to increase developers productivity is definitely its greatest strength. If the tool is used appropriately it can help us be more efficient by decreasing
Added

2023-02-10 17:36 UTC, Melisa-Zorraindo commented
This PR is not yet ready to merge. I'll add a link to a practical example of chatGPT used in the context of frontend development and update this PR soon.

2023-03-08 11:22 UTC, Fermain requested changes
This is a good quality case study about a compelling subject. There is only one issue, you are deleting the tensorflow case study! This will remove someone else's work from the main branch. Please remerge main and un-delete this file.

2023-03-08 12:58 UTC, merged