Study case - Vite js as development platform
NoroffFEU/development-platforms pull request #61
Opened 2023-02-19 13:46 UTC by LAakerberg

My study case is about Vite js as a development platform.

2023-03-08 11:32 UTC, Fermain requested changes
This is a highly detailed and well constructed case study on a crucial tool. There is only one issue highlighted below. This is a matter of tone rather than content. Overall I enjoyed reading your case study. Thank you for your contribution, we will be able to merge with this one change.

2023-03-19 17:28 UTC, LAakerberg commented on vitejs-case-study.md
> +I have chosen to learn more about what a bundler is and why we need to have them. I wanted to dig in and learn more about the building tool Vite js.
Updated have been done with new introduction.

2023-03-19 17:29 UTC, LAakerberg commented
Changes have been done.

2023-05-09 06:25 UTC, Fermain approved these changes
Thank you for this detailed and informative contribution

2023-05-09 06:25 UTC, merged